### ISSUE TITLE
guide papers to understanding

### ISSUE THREAD

**Issue by eugene-renoir** [harvardnlp/compound-pcfg#2]
Hi @yoonkim 
Could you introduce me to the guide papers to understand the paper (not all the references)? I have been tried several times to understand your PCFG paper, but it is not easy.

(I know studying all the references of this paper is the best way to understand that.. However, I'm just a beginner who studies the CS224N which is an NLP course at Stanford University. Reading all the references for each reference paper is almost impossible for me.)

+
If you don't mind, could you share the experiences about OpenNMT to me? I hope to know what am I have to do if I want to make Speech recognition and NMT in the future. 

Thank you

**Comment by adamxyang** [comment]
I found these two resources quite helpful: 
1. https://medium.com/@ryancotterell/a-review-of-compound-probabilistic-context-free-grammars-for-grammar-induction-2cd24ad060cf
2. http://www.people.fas.harvard.edu/~yoonkim/data/comp-pcfg-slides.pdf

To summarise, the compound PCFG model is a VAE with a LSTM encoder and a PCFG decoder.

**Comment by eugene-renoir** [comment]
@Iron4dam Thank you for your kind reply. I'll read them :)
