### ISSUE TITLE
Extra indents in PCFG.py?

### ISSUE THREAD

**Issue by adamxyang** [harvardnlp/compound-pcfg#4]
Are these extra indents in line 70-71 in PCFG.py?
https://github.com/harvardnlp/compound-pcfg/blob/47a7b163b76e6c00aa6c7014c34436b95c6796ef/PCFG.py#L70-L72
Should it be:
```
    log_Z = self.beta[:, 0, n-1, :self.nt_states] + root_scores
    log_Z = self.logsumexp(log_Z, 1)
    return log_Z
```

**Comment by yoonkim** [comment]
Oops, yep you are right. Just fixed it, thanks!
(obviously doesn't change the results, but it would slightly affect time/memory efficiency)
