### ISSUE TITLE
a fast implementation of C-PCFGs

### ISSUE THREAD

**Issue by zhaoyanpeng** [harvardnlp/compound-pcfg#6]
Hi Yoon! Thank you for sharing the amazing code. I re-implemented C-PCFGs based on [Torch-Struct](https://github.com/harvardnlp/pytorch-struct). It is faster (~25min / epoch) and slightly more accurate (~55.7% F1). I am happy to share it. It may help people explore the potential of C-PCFGs more easily. Here is my [implementation](https://github.com/zhaoyanpeng/cpcfg).

-Yanpeng

**Comment by yoonkim** [comment]
Very cool! I have added a link to your repo in the README.

Also, your empirical study of compound PCFGs is very interesting! For the multilingual experiments, did you ever try training with the *same* PCFG for the different languages? I was thinking one could have an additional "language embedding" for each language that is combined with global symbol embeddings (which is shared across all languages) to derive rule probabilities. Amongst other use cases, language embeddings learned this way could be useful for language typology (as has been done with multilingual RNN language models and translation models, e.g. as in https://www.mitpressjournals.org/doi/full/10.1162/COLI_a_00351).

**Comment by srush** [comment]
Awesome! Thanks for sharing.

**Comment by zhaoyanpeng** [comment]
Interesting idea! Language embeddings learned this way would be structurally informative. We can use them to analyze language typology and compare them with language embeddings (more about semantics I think) leaned in multilingual language / translation models. This can be an effort in separating syntax from semantics. I am interested in this direction and will definitely look into your suggestion. Thank you for sharing the idea. Will update you.
